use graftvm_liternal::Liternal;

#[derive(Clone)]
pub struct Addr {
    pub window: usize,
    pub slot: usize,
}

#[derive(Clone)]
pub enum Opcode {
    AddI8 { dst: Addr, lhs: Addr, rhs: Addr },
    SubI8 { dst: Addr, lhs: Addr, rhs: Addr },
    MulI8 { dst: Addr, lhs: Addr, rhs: Addr },
    DivI8 { dst: Addr, lhs: Addr, rhs: Addr },
    RemI8 { dst: Addr, lhs: Addr, rhs: Addr },
    NegI8 { dst: Addr, src: Addr },

    AddI16 { dst: Addr, lhs: Addr, rhs: Addr },
    SubI16 { dst: Addr, lhs: Addr, rhs: Addr },
    MulI16 { dst: Addr, lhs: Addr, rhs: Addr },
    DivI16 { dst: Addr, lhs: Addr, rhs: Addr },
    RemI16 { dst: Addr, lhs: Addr, rhs: Addr },
    NegI16 { dst: Addr, src: Addr },

    AddI32 { dst: Addr, lhs: Addr, rhs: Addr },
    SubI32 { dst: Addr, lhs: Addr, rhs: Addr },
    MulI32 { dst: Addr, lhs: Addr, rhs: Addr },
    DivI32 { dst: Addr, lhs: Addr, rhs: Addr },
    RemI32 { dst: Addr, lhs: Addr, rhs: Addr },
    NegI32 { dst: Addr, src: Addr },

    AddI64 { dst: Addr, lhs: Addr, rhs: Addr },
    SubI64 { dst: Addr, lhs: Addr, rhs: Addr },
    MulI64 { dst: Addr, lhs: Addr, rhs: Addr },
    DivI64 { dst: Addr, lhs: Addr, rhs: Addr },
    RemI64 { dst: Addr, lhs: Addr, rhs: Addr },
    NegI64 { dst: Addr, src: Addr },

    AddU8 { dst: Addr, lhs: Addr, rhs: Addr },
    SubU8 { dst: Addr, lhs: Addr, rhs: Addr },
    MulU8 { dst: Addr, lhs: Addr, rhs: Addr },
    DivU8 { dst: Addr, lhs: Addr, rhs: Addr },
    RemU8 { dst: Addr, lhs: Addr, rhs: Addr },

    AddU16 { dst: Addr, lhs: Addr, rhs: Addr },
    SubU16 { dst: Addr, lhs: Addr, rhs: Addr },
    MulU16 { dst: Addr, lhs: Addr, rhs: Addr },
    DivU16 { dst: Addr, lhs: Addr, rhs: Addr },
    RemU16 { dst: Addr, lhs: Addr, rhs: Addr },

    AddU32 { dst: Addr, lhs: Addr, rhs: Addr },
    SubU32 { dst: Addr, lhs: Addr, rhs: Addr },
    MulU32 { dst: Addr, lhs: Addr, rhs: Addr },
    DivU32 { dst: Addr, lhs: Addr, rhs: Addr },
    RemU32 { dst: Addr, lhs: Addr, rhs: Addr },

    AddU64 { dst: Addr, lhs: Addr, rhs: Addr },
    SubU64 { dst: Addr, lhs: Addr, rhs: Addr },
    MulU64 { dst: Addr, lhs: Addr, rhs: Addr },
    DivU64 { dst: Addr, lhs: Addr, rhs: Addr },
    RemU64 { dst: Addr, lhs: Addr, rhs: Addr },

    AddF32 { dst: Addr, lhs: Addr, rhs: Addr },
    SubF32 { dst: Addr, lhs: Addr, rhs: Addr },
    MulF32 { dst: Addr, lhs: Addr, rhs: Addr },
    DivF32 { dst: Addr, lhs: Addr, rhs: Addr },
    RemF32 { dst: Addr, lhs: Addr, rhs: Addr },
    NegF32 { dst: Addr, src: Addr },

    AddF64 { dst: Addr, lhs: Addr, rhs: Addr },
    SubF64 { dst: Addr, lhs: Addr, rhs: Addr },
    MulF64 { dst: Addr, lhs: Addr, rhs: Addr },
    DivF64 { dst: Addr, lhs: Addr, rhs: Addr },
    RemF64 { dst: Addr, lhs: Addr, rhs: Addr },
    NegF64 { dst: Addr, src: Addr },

    LtI8 { dst: Addr, lhs: Addr, rhs: Addr },
    LtI16 { dst: Addr, lhs: Addr, rhs: Addr },
    LtI32 { dst: Addr, lhs: Addr, rhs: Addr },
    LtI64 { dst: Addr, lhs: Addr, rhs: Addr },
    LtU8 { dst: Addr, lhs: Addr, rhs: Addr },
    LtU16 { dst: Addr, lhs: Addr, rhs: Addr },
    LtU32 { dst: Addr, lhs: Addr, rhs: Addr },
    LtU64 { dst: Addr, lhs: Addr, rhs: Addr },
    LtF32 { dst: Addr, lhs: Addr, rhs: Addr },
    LtF64 { dst: Addr, lhs: Addr, rhs: Addr },

    LeI8 { dst: Addr, lhs: Addr, rhs: Addr },
    LeI16 { dst: Addr, lhs: Addr, rhs: Addr },
    LeI32 { dst: Addr, lhs: Addr, rhs: Addr },
    LeI64 { dst: Addr, lhs: Addr, rhs: Addr },
    LeU8 { dst: Addr, lhs: Addr, rhs: Addr },
    LeU16 { dst: Addr, lhs: Addr, rhs: Addr },
    LeU32 { dst: Addr, lhs: Addr, rhs: Addr },
    LeU64 { dst: Addr, lhs: Addr, rhs: Addr },
    LeF32 { dst: Addr, lhs: Addr, rhs: Addr },
    LeF64 { dst: Addr, lhs: Addr, rhs: Addr },

    GtI8 { dst: Addr, lhs: Addr, rhs: Addr },
    GtI16 { dst: Addr, lhs: Addr, rhs: Addr },
    GtI32 { dst: Addr, lhs: Addr, rhs: Addr },
    GtI64 { dst: Addr, lhs: Addr, rhs: Addr },
    GtU8 { dst: Addr, lhs: Addr, rhs: Addr },
    GtU16 { dst: Addr, lhs: Addr, rhs: Addr },
    GtU32 { dst: Addr, lhs: Addr, rhs: Addr },
    GtU64 { dst: Addr, lhs: Addr, rhs: Addr },
    GtF32 { dst: Addr, lhs: Addr, rhs: Addr },
    GtF64 { dst: Addr, lhs: Addr, rhs: Addr },

    GeI8 { dst: Addr, lhs: Addr, rhs: Addr },
    GeI16 { dst: Addr, lhs: Addr, rhs: Addr },
    GeI32 { dst: Addr, lhs: Addr, rhs: Addr },
    GeI64 { dst: Addr, lhs: Addr, rhs: Addr },
    GeU8 { dst: Addr, lhs: Addr, rhs: Addr },
    GeU16 { dst: Addr, lhs: Addr, rhs: Addr },
    GeU32 { dst: Addr, lhs: Addr, rhs: Addr },
    GeU64 { dst: Addr, lhs: Addr, rhs: Addr },
    GeF32 { dst: Addr, lhs: Addr, rhs: Addr },
    GeF64 { dst: Addr, lhs: Addr, rhs: Addr },

    AndI8 { dst: Addr, lhs: Addr, rhs: Addr },
    AndI16 { dst: Addr, lhs: Addr, rhs: Addr },
    AndI32 { dst: Addr, lhs: Addr, rhs: Addr },
    AndI64 { dst: Addr, lhs: Addr, rhs: Addr },

    OrI8 { dst: Addr, lhs: Addr, rhs: Addr },
    OrI16 { dst: Addr, lhs: Addr, rhs: Addr },
    OrI32 { dst: Addr, lhs: Addr, rhs: Addr },
    OrI64 { dst: Addr, lhs: Addr, rhs: Addr },

    XorI8 { dst: Addr, lhs: Addr, rhs: Addr },
    XorI16 { dst: Addr, lhs: Addr, rhs: Addr },
    XorI32 { dst: Addr, lhs: Addr, rhs: Addr },
    XorI64 { dst: Addr, lhs: Addr, rhs: Addr },

    NotI8 { dst: Addr, src: Addr },
    NotI16 { dst: Addr, src: Addr },
    NotI32 { dst: Addr, src: Addr },
    NotI64 { dst: Addr, src: Addr },

    AndU8 { dst: Addr, lhs: Addr, rhs: Addr },
    AndU16 { dst: Addr, lhs: Addr, rhs: Addr },
    AndU32 { dst: Addr, lhs: Addr, rhs: Addr },
    AndU64 { dst: Addr, lhs: Addr, rhs: Addr },

    OrU8 { dst: Addr, lhs: Addr, rhs: Addr },
    OrU16 { dst: Addr, lhs: Addr, rhs: Addr },
    OrU32 { dst: Addr, lhs: Addr, rhs: Addr },
    OrU64 { dst: Addr, lhs: Addr, rhs: Addr },

    XorU8 { dst: Addr, lhs: Addr, rhs: Addr },
    XorU16 { dst: Addr, lhs: Addr, rhs: Addr },
    XorU32 { dst: Addr, lhs: Addr, rhs: Addr },
    XorU64 { dst: Addr, lhs: Addr, rhs: Addr },

    NotU8 { dst: Addr, src: Addr },
    NotU16 { dst: Addr, src: Addr },
    NotU32 { dst: Addr, src: Addr },
    NotU64 { dst: Addr, src: Addr },

    ShlI8 { dst: Addr, lhs: Addr, rhs: Addr },
    ShlI16 { dst: Addr, lhs: Addr, rhs: Addr },
    ShlI32 { dst: Addr, lhs: Addr, rhs: Addr },
    ShlI64 { dst: Addr, lhs: Addr, rhs: Addr },
    ShlU8 { dst: Addr, lhs: Addr, rhs: Addr },
    ShlU16 { dst: Addr, lhs: Addr, rhs: Addr },
    ShlU32 { dst: Addr, lhs: Addr, rhs: Addr },
    ShlU64 { dst: Addr, lhs: Addr, rhs: Addr },

    ShrI8 { dst: Addr, lhs: Addr, rhs: Addr },
    ShrI16 { dst: Addr, lhs: Addr, rhs: Addr },
    ShrI32 { dst: Addr, lhs: Addr, rhs: Addr },
    ShrI64 { dst: Addr, lhs: Addr, rhs: Addr },
    ShrU8 { dst: Addr, lhs: Addr, rhs: Addr },
    ShrU16 { dst: Addr, lhs: Addr, rhs: Addr },
    ShrU32 { dst: Addr, lhs: Addr, rhs: Addr },
    ShrU64 { dst: Addr, lhs: Addr, rhs: Addr },

    ExtendI8I16 { dst: Addr, src: Addr },
    ExtendI8I32 { dst: Addr, src: Addr },
    ExtendI8I64 { dst: Addr, src: Addr },
    ExtendI16I32 { dst: Addr, src: Addr },
    ExtendI16I64 { dst: Addr, src: Addr },
    ExtendI32I64 { dst: Addr, src: Addr },

    ExtendU8U16 { dst: Addr, src: Addr },
    ExtendU8U32 { dst: Addr, src: Addr },
    ExtendU8U64 { dst: Addr, src: Addr },
    ExtendU16U32 { dst: Addr, src: Addr },
    ExtendU16U64 { dst: Addr, src: Addr },
    ExtendU32U64 { dst: Addr, src: Addr },

    TruncI64I32 { dst: Addr, src: Addr },
    TruncI64I16 { dst: Addr, src: Addr },
    TruncI64I8 { dst: Addr, src: Addr },
    TruncI32I16 { dst: Addr, src: Addr },
    TruncI32I8 { dst: Addr, src: Addr },
    TruncI16I8 { dst: Addr, src: Addr },

    ReinterpretU8I8 { dst: Addr, src: Addr },
    ReinterpretU16I16 { dst: Addr, src: Addr },
    ReinterpretU32I32 { dst: Addr, src: Addr },
    ReinterpretU64I64 { dst: Addr, src: Addr },
    ReinterpretI8U8 { dst: Addr, src: Addr },
    ReinterpretI16U16 { dst: Addr, src: Addr },
    ReinterpretI32U32 { dst: Addr, src: Addr },
    ReinterpretI64U64 { dst: Addr, src: Addr },

    IntToF32 { dst: Addr, src: Addr },
    IntToF64 { dst: Addr, src: Addr },
    UIntToF32 { dst: Addr, src: Addr },
    UIntToF64 { dst: Addr, src: Addr },
    FToI32 { dst: Addr, src: Addr },
    FToI64 { dst: Addr, src: Addr },
    FToU32 { dst: Addr, src: Addr },
    FToU64 { dst: Addr, src: Addr },

    Eq { lhs: Addr, rhs: Addr },
    Neq { lhs: Addr, rhs: Addr },

    Jump(usize),
    Branch(usize),

    StoreData { index: usize, data: Liternal },
    LoadData { dst: Addr, index: usize },

    Move { dst: Addr, src: Addr },
    Copy { dst: Addr, src: Addr },
    Drop { src: Addr },

    Enter,
    Exit,
}

pub type Bytecode = Vec<Opcode>;
